Delete row with optional confirm and custom confirmMessage. Delete action with custom message. All using translations.
BadChoice/thrust pull request #104
Opened 2021-06-07 09:52 UTC by aleixgil

Linear: https://linear.app/revo/issue/REV-4119/thrust-confirmation-option-and-message-in-delete-field-and-action

Reviewer: @PauRevo

2021-11-11 15:20 UTC, PauBenetPrat approved these changes

2021-11-11 15:21 UTC, PauBenetPrat approved these changes

2021-11-12 10:57 UTC, BadChoice requested changes

2021-11-12 10:57 UTC, BadChoice commented on src/Actions/Action.php
> +    public $actionConfirmationMessage = 'Are you sure';
perque li canviem el nom

2021-11-12 10:57 UTC, BadChoice commented on src/Actions/Action.php
> +        return Translation::useTranslationPrefix(Str::camel($this->actionConfirmationMessage), $this->actionConfirmationMessage ? $this->actionConfirmationMessage.'?' : $this->actionConfirmationMessa
aixo ho veig massa complicat perque estigui aquí, no ho pot fer tot el mateix translation? i fer nomes
Translation::translate($this->actionConfirmationMessage)

2021-11-12 10:57 UTC, BadChoice commented on src/Fields/Delete.php
> +        $escapedConfirmMessage = htmlentities($this->getDeleteConfirmationMessage(), ENT_QUOTES);
perque serveix tot aixo? no ho podem encapsular i posar-hi un nom?

2021-11-12 10:57 UTC, BadChoice commented on src/Fields/Field.php
> +        return Translation::useTranslationPrefix(Str::camel($this->deleteConfirmationMessage), $this->deleteConfirmationMessage ? $this->deleteConfirmationMessage.'?' : $this->deleteConfirmationMessa
com abans, seria bo Translation::translate($this->deleteConfirmationMEsssage)

2021-11-12 10:57 UTC, BadChoice commented on src/resources/js/utils.js
> +        let confirmDeleteMessage = $(this).attr('confirm-message');
posem el missatge al attr?

2021-11-12 15:13 UTC, aleixgil commented on src/resources/js/utils.js
> +        let confirmDeleteMessage = $(this).attr('confirm-message');
No el posem, l'agafem el deleteMessage del atribut confirm-message que he afegit al Fields/Delete.php

2021-11-19 10:06 UTC, BadChoice approved these changes

2021-11-19 10:06 UTC, merged