Sortable resources allow being sorted by request
BadChoice/thrust pull request #85
Opened 2021-04-15 09:22 UTC by MartiSalaMorral

Added ClearSorting main action

2021-04-15 13:23 UTC, BadChoice requested changes

2021-04-15 13:23 UTC, BadChoice commented on src/Resource.php
> +        if (request('sort') && $this->sortFieldIsValid(request('sort'))) {
no ho faries amb un negat i fer return si no hi ha sorto no es valid?

2021-04-15 13:23 UTC, BadChoice commented on src/resources/views/components/mainActions.blade.php
> +        if (request('sort')) {
sortira sempre? nomes hauria de sortir si es sortable no?

2021-04-15 13:23 UTC, BadChoice commented on src/resources/views/indexTable.blade.php
> +            @if ($sortable && !request('sort'))
aquesta comprovació l'afegim a molts llocs, potser estaria bé encapsular-la e una funcio

2021-04-20 09:36 UTC, MartiSalaMorral commented on src/resources/views/components/mainActions.blade.php
> +        if (request('sort')) {
No, crec que això hauria de sortir sempre. El que fa és netejar els paràmetres de la query per a tornar a tenir l'index ordenat com estava al principi independentment de si el recurs és sortable o no.

2021-04-20 10:30 UTC, BadChoice approved these changes

2021-04-20 10:30 UTC, merged