Optional Confirmation option when update thrust Resource.
BadChoice/thrust pull request #97
Opened 2021-05-17 09:10 UTC by aleixgil

Usage:
    public $confirmationMessage = 'message'; 
if 'message' is in thrustTranslationPrefix file (e.g. admin.message), will print translation, otherwise will print raw 'message'.

!!!!! TREURE TAAGGGG YA PLSSS !!!!!

Screenshot:
<img width="1432" alt="Captura de pantalla 2021-05-17 a las 11 01 51" src="https://user-images.githubusercontent.com/29859922/118463691-58a4a400-b700-11eb-955e-c31b22dfb285.png">

Reviewer: @PauRevo

2021-05-17 11:29 UTC, BadChoice requested changes

2021-05-17 11:29 UTC, BadChoice commented on src/Resource.php
> +    public function getConfirmation()
no m'agrada aixo dins del resource, fa masses coses
aixo de les traduccions ho fem a varis llocs no?
si es així podriem crear una classe que s'encarregues de les traduccions i unificar-ho tot

2021-05-17 13:25 UTC, aleixgil commented on src/Resource.php
> +    public function getConfirmation()
Peró el getConfirmation no va de traduccions, on ho posaries sino? ha de passar per aqui...

2021-06-04 14:35 UTC, PauBenetPrat commented
@BadChoice continuarem mantenint aquest paquest o farem anar el de revosystems?
@aleixgil si es per xef o retail avisam.

2021-06-04 14:38 UTC, aleixgil commented
@PauBenetPrat serà pels dos, XEF i RETAlL.

2021-06-04 14:50 UTC, PauBenetPrat commented
Ok, quan el Jordi t'ho aprovi faig merge cap al fork revosystems/thrust ja que a partir de laravel8 fem anar aquest altre paquet.

2021-06-04 14:51 UTC, aleixgil commented
Okay 👌🏽

2021-06-07 07:29 UTC, BadChoice approved these changes

2021-06-07 07:29 UTC, BadChoice commented
Pots fer el del delete tb

2021-06-07 07:29 UTC, merged

2021-06-07 07:31 UTC, aleixgil commented
@BadChoice Sip l'estic fent el delete tmb. però fora d'aquest PR, pq és més complicat que el edit i hi han 2 delete (field i action). He preferit separar-ho.